[project]
name = "mna_due_diligence"
version = "0.1.0"
description = "Modules for MNA Due Diligence contract intelligence agent"
authors = [
    { name="Aditya Anurag", email="a.anurag1024@gmail.com" }
]
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "docling", 
    "docling-core",
    "structlog",
    "pydantic-settings",
    "sqlalchemy[asyncio]",
    "aiomysql",
    "fastembed-gpu",
    "qdrant-client",
    "pandas",
    "cryptography",
    "openai",
    "mcp"
]

[tool.uv]
extra-index-url = ["https://download.pytorch.org/whl/cu121"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["mna_due_diligence*"]